language: python

python:
  - "3.8"

before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out travis_rsa -d

install:
  - pip install -r requirements.txt

script:
  - flake8

deploy:
  provider: script
  script: chmod +x deploy.sh && ./deploy.sh
  on:
    branch: dev