# Generated by Django 3.0.4 on 2020-03-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfrage', models.CharField(max_length=240)),
                ('zeit', models.DateTimeField()),
                ('laenge', models.PositiveIntegerField()),
            ],
        ),
    ]
