# Generated by Django 3.0.4 on 2020-03-21 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunden_email', models.EmailField(max_length=254)),
                ('text', models.CharField(max_length=500)),
                ('start_datum', models.DateTimeField()),
                ('end_datum', models.DateTimeField()),
                ('approved', models.BooleanField()),
                ('unternehmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
