# Generated by Django 3.0.4 on 2020-03-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfrage',
            name='slot',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.TimeSlot'),
            preserve_default=False,
        ),
    ]
