# Generated by Django 3.0.4 on 2020-03-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_anfrage_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anfrage',
            name='end_datum',
        ),
        migrations.RemoveField(
            model_name='anfrage',
            name='start_datum',
        ),
    ]
