# Generated by Django 3.0.4 on 2020-03-21 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20200321_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnternehmensProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('adresse', models.TextField()),
                ('langitude', models.TextField()),
                ('longitude', models.TextField()),
                ('telefon', models.TextField()),
                ('max_pro_slot', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
