# Generated by Django 3.0.4 on 2020-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_unternehmensprofil_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='unternehmensprofil',
            name='available_time_slots',
            field=models.TextField(default="[{start: '10:00', end: '18:00'}]"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unternehmensprofil',
            name='oeffnungszeiten',
            field=models.TextField(default="[{start: '10:00', end: '18:00'}]"),
            preserve_default=False,
        ),
    ]
