# Generated by Django 3.0.4 on 2020-03-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200321_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unternehmensprofil',
            old_name='kategorie',
            new_name='ober_kategorie',
        ),
        migrations.AddField(
            model_name='unternehmensprofil',
            name='unter_kategorien',
            field=models.TextField(default='Genussmittel, Obst & Gemüse'),
            preserve_default=False,
        ),
    ]
