# Generated by Django 3.0.4 on 2020-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_unternehmensprofil_beschreibung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unternehmensprofil',
            name='ober_kategorie',
            field=models.CharField(choices=[('LEB', 'Lebensmittel'), ('BAE', 'Bäckerei'), ('FLE', 'Fleischerei'), ('GET', 'Getränke'), ('DRO', 'Drogerie'), ('ELE', 'Elektronik'), ('HWO', 'Haushalt & Wohnen'), ('WEB', 'Werkeln & Basteln'), ('SPO', 'Sport'), ('UNT', 'Unterhaltung'), ('MOD', 'Mode'), ('APO', 'Apotheke'), ('KIO', 'Zeitungen & Kiosk'), ('BUC', 'Bücher'), ('TIE', 'Tierbedarf'), ('BLU', 'Blumenladen'), ('OUT', 'Outdoor'), ('SON', 'Sonstiges'), ('RAU', 'Raucherbedarf')], max_length=3),
        ),
    ]
