# Generated by Django 3.0.4 on 2020-03-22 16:19

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20200322_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unternehmensprofil',
            name='available_time_slots',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='unternehmensprofil',
            name='oeffnungszeiten',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.CreateModel(
            name='SlotsDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('unternehmen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SlotsDay'),
        ),
    ]
