# Generated by Django 3.0.4 on 2020-03-25 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_auto_20200322_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='unternehmen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SlotsDay',
        ),
    ]
