# Generated by Django 3.0.4 on 2020-03-26 15:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200325_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unternehmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('adresse', models.TextField()),
                ('langitude', models.TextField()),
                ('longitude', models.TextField()),
                ('telefon', models.TextField()),
                ('max_pro_slot', models.PositiveSmallIntegerField()),
                ('oeffnungszeiten', django.contrib.postgres.fields.jsonb.JSONField()),
                ('beschreibung', models.TextField()),
                ('ober_kategorie', models.CharField(choices=[('LEB', 'Lebensmittel'), ('BAE', 'Bäckerei'), ('FLE', 'Fleischerei'), ('GET', 'Getränke'), ('DRO', 'Drogerie'), ('ELE', 'Elektronik'), ('HWO', 'Haushalt & Wohnen'), ('WEB', 'Werkeln & Basteln'), ('SPO', 'Sport'), ('UNT', 'Unterhaltung'), ('MOD', 'Mode'), ('APO', 'Apotheke'), ('KIO', 'Zeitungen & Kiosk'), ('BUe', 'Bücher'), ('TIE', 'Tierbedarf'), ('BLU', 'Blumenladen'), ('OUT', 'Outdoor'), ('SON', 'Sonstiges'), ('RAU', 'Raucherbedarf'), ('SPI', 'Spielwaren'), ('SCH', 'Schuhe')], max_length=3)),
                ('unter_kategorien', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='anfrage',
            name='unternehmen_id',
        ),
        migrations.DeleteModel(
            name='UnternehmensProfil',
        ),
        migrations.AddField(
            model_name='anfrage',
            name='unternehmen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Unternehmen'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='unternehmen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Unternehmen'),
        ),
    ]
