# Generated by Django 3.0.4 on 2020-03-27 17:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200326_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unternehmen',
            name='langitude',
        ),
        migrations.RemoveField(
            model_name='unternehmen',
            name='longitude',
        ),
        migrations.AddField(
            model_name='unternehmen',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
