# Generated by Django 3.0.4 on 2020-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_kategorien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unternehmen',
            name='ober_kategorie',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='unternehmen',
            name='unter_kategorien',
            field=models.CharField(max_length=4),
        ),
    ]
