# Generated by Django 3.0.4 on 2020-03-28 16:16

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200328_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorien',
            name='ober',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), size=2), size=None),
        ),
        migrations.AlterField(
            model_name='kategorien',
            name='unter',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), size=2), size=None),
        ),
    ]
