# Generated by Django 3.0.4 on 2020-03-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200329_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anfrage',
            old_name='unternehmen',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='unternehmen',
            new_name='company',
        ),
    ]
