# Generated by Django 3.0.4 on 2020-03-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200329_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnterKategorie',
            new_name='SubCategory',
        ),
    ]
