# Generated by Django 3.0.4 on 2020-03-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200329_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='point',
            new_name='location',
        ),
    ]
