# Generated by Django 3.0.4 on 2020-03-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200329_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='oeffnungszeiten',
            new_name='business_hours',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='beschreibung',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='max_pro_slot',
            new_name='max_per_slot',
        ),
    ]
