# Generated by Django 3.0.4 on 2020-03-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200329_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ober_kategorien',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='unter_kategorien',
            new_name='sub_categories',
        ),
    ]
