# Generated by Django 3.0.4 on 2020-03-29 12:33

from django.db import migrations


def migrate_categories(apps, schema_editor):
    Category = apps.get_model("api", "Category")
    Company = apps.get_model("api", "Company")

    mig_cat, created = Category.objects.get_or_create(name="MIGRATION", slug="MIG")
    Company.objects.filter(category__isnull=True).update(category=mig_cat)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200329_1432'),
    ]

    operations = [
        migrations.RunPython(migrate_categories)
    ]
