# Generated by Django 3.0.4 on 2020-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200329_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=False, help_text='The company is only listed in the map when this flag is active'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='max_per_slot',
            field=models.PositiveSmallIntegerField(help_text='Maximum number of persons who can book a particular time slot'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(help_text='Use international format: e.g. +491235565', max_length=30),
        ),
    ]
