# Generated by Django 3.0.4 on 2020-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200329_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='business_hours',
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_friday_end',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_friday_start',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_monday_end',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_monday_start',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_saturday_end',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_saturday_start',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_sunday_end',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_sunday_start',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_thursday_end',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_thursday_start',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_tuesday_end',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_tuesday_start',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_wednesday_end',
            field=models.TimeField(default='18:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='business_hours_wednesday_start',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
    ]
