# Generated by Django 3.0.4 on 2020-03-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200329_1758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessHoursWeekday',
            new_name='BusinessHours',
        ),
    ]
