# Generated by Django 3.0.4 on 2020-03-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20200331_1743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('start', 'end', 'company')},
        ),
    ]
