# Generated by Django 3.0.4 on 2020-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20200403_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, to='api.SubCategory'),
        ),
    ]
